[package]
name = "bot-rs"
version = "0.1.0"
authors = ["justincremer <jacremer@live.com>"]
edition = "2018"

[dependencies]
serenity = "0.10"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

